command:
- "python"
- "app.py"

env:
- name: "SPACE_ID"
  valueFrom: "genie-space"
- name: "SERVING_ENDPOINT_NAME"
  valueFrom: "serving-endpoint"
- name: "VISUALIZATION_ENDPOINT_NAME"
  valueFrom: "visualization-endpoint"

authorization:
  type: oauth
  scopes:
    - genie
    - sql
